apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  namespace: guestbook-ab-test-a
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - env:
        - name: FOO
          value: bar
        - containerPort: 3000
          name: http
        image: ghcr.io/frimik/guestbook:v0.0.2
        name: guestbook
        ports: null
